"""Update Cords

Revision ID: 7e46fd0f39b9
Revises: cecc0f11aed2
Create Date: 2025-08-03 00:03:22.845102

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e46fd0f39b9'
down_revision: Union[str, Sequence[str], None] = 'cecc0f11aed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'cords',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'cords',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               existing_nullable=False)
    # ### end Alembic commands ###
