name: "project-check"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"
jobs:
  linter:
    name: "Python linter"
    runs-on: "ubuntu-latest"

    container:
      image: "hanyuu/python:wps-slim"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Run linter"
        run: "flake8 app/"

  tests:
    name: "Pytest"
    needs: ["linter"]
    runs-on: "ubuntu-latest"

    services:
      postgres:
        image: "postgis/postgis:17-3.5"
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: "orgz"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      elasticsearch:
        image: "elasticsearch:8.11.3"
        ports:
          - "9200:9200"
        env:
          discovery.type: "single-node"
          xpack.security.enabled: "false"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        options: >-
          --health-cmd "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      ORGZ_DATA_BASE_DSN: "postgresql+asyncpg://postgres:postgres@postgres:5432/orgz"
      ORGZ_ELASTIC_HOST: "http://elasticsearch:9200"

    container:
      image: "hanyuu/python:pytest-slim"

    steps:
      - uses: "actions/checkout@v4"

      - name: "Install dependencies"
        run: "poetry install --no-root"

      - name: "Run tests"
        run: "poetry run pytest"
